using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

// Define the namespace for our service
namespace DotNetReportService.Services
{
    // This is the service class that does the work
    public class PdfService
    {
        public byte[] GenerateYieldReport()
        {
            // QuestPDF requires this license configuration
            QuestPDF.Settings.License = LicenseType.Community;

            // Generate the PDF document using QuestPDF's fluent API
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    // Page settings
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(style => style.FontSize(12));

                    // Header
                    page.Header()
                        .Text("Smart Agriculture Yield Report")
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                    // Content
                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(col =>
                        {
                            col.Spacing(20);
                            col.Item().Text("This is a sample yield report generated by the .NET service.");
                            col.Item().Text("Later, the Java service will send data (like a list of SensorReadings) to this endpoint, and this service will format that data into a professional table.");
                        });

                    // Footer
                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                });
            });

            // Return the generated PDF as a byte array
            byte[] pdfBytes = document.GeneratePdf();
            return pdfBytes;
        }
    }
}